version: '3'
services:
  cassandra:
    image: cassandra:4.1.2
    container_name: cassandra-container
    ports:
      - 9042:9042
    volumes:
      - ./db:/db
      - ./cassandra-data:/var/lib/cassandra
    command: ["cassandra", "-f"]
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - app-network
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_KEYSPACE=benediction_keyspace
    depends_on:
      cassandra:
        condition: service_healthy

networks:
  app-network: