version: '3'
services:
  cassandra:
    image: cassandra:4.1.2
    container_name: cassandra-container
    ports:
      - 9042:9042
    volumes:
      - ./db:/db
      - ./cassandra-data:/var/lib/cassandra
    command: ["cassandra", "-f"]
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
  app-network: